# Generated by Django 5.2.4 on 2025-09-19 16:50

import master.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classname',
            options={'ordering': ['year', 'name']},
        ),
        migrations.AlterModelOptions(
            name='classsubject',
            options={'ordering': ['class_name__year', 'class_name__name', 'section__name', 'order', 'subject__name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['class_name__year', 'class_name__name', 'name']},
        ),
        migrations.AddField(
            model_name='classname',
            name='year',
            field=models.PositiveIntegerField(db_index=True, default=master.models.current_year),
        ),
        migrations.AlterField(
            model_name='classname',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='classname',
            constraint=models.UniqueConstraint(fields=('name', 'year'), name='uniq_classname_name_year'),
        ),
    ]
