# Generated by Django 5.2.4 on 2025-09-05 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_section_classname_sections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classname',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='section',
            name='is_active',
        ),
        migrations.AddField(
            model_name='subject',
            name='is_practical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='is_theory',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='classname',
            unique_together={('name',)},
        ),
    ]
