# Generated by Django 5.2.4 on 2025-09-05 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_alter_classname_options_remove_section_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['class_name__name', 'name']},
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('class_name', 'name')},
        ),
    ]
