# Generated by Django 5.2.4 on 2025-09-06 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_alter_subject_options_alter_subject_unique_together'),
        ('people', '0007_teacher_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_compulsory', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['class_name__name', 'section__name', 'order', 'subject__name'],
            },
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='GalleryItem',
        ),
        migrations.AlterUniqueTogether(
            name='classname',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='classname',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_subjects', to='master.classname'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='master.section'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='master.subject'),
        ),
        migrations.AddField(
            model_name='classsubject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_subjects', to='people.teacher'),
        ),
        migrations.AddIndex(
            model_name='classsubject',
            index=models.Index(fields=['class_name', 'section'], name='master_clas_class_n_a5f543_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classsubject',
            unique_together={('section', 'subject')},
        ),
    ]
