# Generated by Django 5.2.4 on 2025-09-15 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('people', '0003_alter_student_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='master.section'),
            preserve_default=False,
        ),
    ]
