# Generated by Django 5.2.4 on 2025-09-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_teacher_teacher_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
