# Generated by Django 5.2.4 on 2025-09-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('government_approval_number', models.CharField(blank=True, max_length=100)),
                ('government_approval_date', models.DateField(blank=True, null=True)),
                ('history', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('objective', models.TextField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('address_code', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institution_logos/')),
                ('institution_image', models.ImageField(blank=True, null=True, upload_to='institution_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ManagingCommitteeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='committee_photos/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalVicePrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(max_length=150)),
                ('designation', models.CharField(choices=[('principal', 'Principal'), ('vice_principal', 'Vice Principal'), ('headmaster', 'Headmaster'), ('headmistress', 'Headmistress')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
