# Generated by Django 5.2.4 on 2025-09-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0010_notice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='principalviceprincipal',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
