# Generated by Django 5.2.4 on 2025-09-21 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0002_alter_classname_options_alter_classsubject_options_and_more'),
        ('people', '0004_alter_student_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExamRoutine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=50)),
                ('section', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('file', models.FileField(upload_to='routine_files/')),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('section', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='syllabus_files/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.classname')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.section')),
            ],
            options={
                'unique_together': {('class_name', 'section', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('exam_name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='result_files/')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='master.classname')),
            ],
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3)),
                ('period', models.CharField(blank=True, max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_rows', to='master.classname')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_rows', to='academics.classroom')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_rows', to='master.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_rows', to='master.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_rows', to='people.teacher')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time', 'class_name__name', 'section__name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], default='PRESENT', max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marked_attendance', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='people.student')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='academics.timetableentry')),
            ],
            options={
                'ordering': ['-date', 'timetable_id', 'student_id'],
            },
        ),
        migrations.CreateModel(
            name='ExamMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('letter', models.CharField(blank=True, max_length=5)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='academics.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.subject')),
            ],
            options={
                'unique_together': {('exam', 'student', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='GradeBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.PositiveIntegerField()),
                ('max_score', models.PositiveIntegerField()),
                ('letter', models.CharField(max_length=5)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='academics.gradescale')),
            ],
            options={
                'ordering': ['-min_score'],
                'constraints': [models.CheckConstraint(condition=models.Q(('min_score__lte', models.F('max_score'))), name='grades_min_le_max')],
            },
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(fields=('class_name', 'section', 'day_of_week', 'period', 'start_time', 'end_time'), name='uniq_class_section_day_period_time'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('timetable', 'date', 'student'), name='uniq_attendance_row'),
        ),
    ]
