# Generated by Django 5.2.4 on 2025-09-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='gradeband',
            index=models.Index(fields=['scale', 'min_score', 'max_score'], name='idx_scale_range'),
        ),
        migrations.AddConstraint(
            model_name='gradeband',
            constraint=models.CheckConstraint(condition=models.Q(('min_score__gte', 0), ('max_score__lte', 100)), name='grades_within_0_100'),
        ),
        migrations.AddConstraint(
            model_name='gradeband',
            constraint=models.UniqueConstraint(fields=('scale', 'letter'), name='uniq_scale_letter'),
        ),
        migrations.AddConstraint(
            model_name='gradeband',
            constraint=models.UniqueConstraint(fields=('scale', 'min_score', 'max_score'), name='uniq_scale_exact_range'),
        ),
    ]
