# Generated by Django 5.2.4 on 2025-09-13 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('master', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='master.classname'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='master.classname'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='master.section'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='master.subject'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='people.teacher'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_rows', to='master.classname'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_rows', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_rows', to='master.section'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_rows', to='master.subject'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timetable_rows', to='people.teacher'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(fields=('class_name', 'section', 'day_of_week', 'period'), name='uniq_class_section_day_period_assignment'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'day_of_week', 'period'), name='uniq_teacher_day_period_assignment'),
        ),
        migrations.AddConstraint(
            model_name='teacherassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('room__isnull', False), models.Q(('room', ''), _negated=True)), fields=('room', 'day_of_week', 'period'), name='uniq_room_day_period_assignment'),
        ),
        migrations.AddConstraint(
            model_name='timetableentry',
            constraint=models.UniqueConstraint(fields=('class_name', 'section', 'day_of_week', 'period', 'start_time', 'end_time'), name='uniq_class_section_day_period_time'),
        ),
    ]
