# Generated by Django 5.2.4 on 2025-09-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
