# Generated by Django 5.2.4 on 2025-09-07 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_timetableentry_room'),
        ('people', '0007_teacher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_rows', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timetable_rows', to='people.teacher'),
        ),
    ]
