# Generated by Django 5.2.4 on 2025-09-15 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherAssignment',
        ),
    ]
