# Generated by Django 5.2.4 on 2025-09-07 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_timetableentry_classroom_timetableentry_teacher'),
        ('master', '0009_classsubject_delete_banner_delete_galleryitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=3)),
                ('period', models.CharField(max_length=50)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='master.classname')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='master.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='master.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['day_of_week', 'period', 'class_name__name', 'section__name'],
                'constraints': [models.UniqueConstraint(fields=('class_name', 'section', 'day_of_week', 'period'), name='uniq_class_section_day_period_assignment'), models.UniqueConstraint(fields=('teacher', 'day_of_week', 'period'), name='uniq_teacher_day_period_assignment'), models.UniqueConstraint(condition=models.Q(('room__isnull', False), models.Q(('room', ''), _negated=True)), fields=('room', 'day_of_week', 'period'), name='uniq_room_day_period_assignment')],
            },
        ),
    ]
