# Generated by Django 5.2.4 on 2025-09-18 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_delete_teacherassignment'),
        ('people', '0004_alter_student_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('EXCUSED', 'Excused')], default='PRESENT', max_length=10)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marked_attendance', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='people.student')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='academics.timetableentry')),
            ],
            options={
                'ordering': ['-date', 'timetable_id', 'student_id'],
                'constraints': [models.UniqueConstraint(fields=('timetable', 'date', 'student'), name='uniq_attendance_row')],
            },
        ),
    ]
