# Generated by Django 5.2.4 on 2025-09-08 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_teacherassignment'),
        ('people', '0007_teacher_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_assignments', to='people.teacher'),
        ),
    ]
